/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The problem object follows the RFC-7807 (https://tools.ietf.org/html/rfc7807)
 */
export type Problem = {
  /**
   * A URI reference [RFC3986] that identifies the problem type
   */
  type?: string;
  /**
   * A short, human-readable summary of the problem type.
   */
  title?: string;
  /**
   * The HTTP status code (RFC7231, Section 6) generated by the origin server for this occurrence of the problem.
   */
  status?: number;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
};

